# Train/val/test sets
train: '/content/fed_dentex/dentex_split/train_15'
val: '/content/fed_dentex/dentex_split/val_1'
test: '/content/fed_dentex/dentex_split/val_1'

# Classes
names:
  0: Impacted
  1: Caries
  2: Periapical Lesion
  3: Deep Caries