# Train/val/test sets
train: '/content/fed_dentex/dentex_split/train_25'
val: '/content/fed_dentex/dentex_split/val_3'
test: '/content/fed_dentex/dentex_split/val_3'

# Classes
names:
  0: Impacted
  1: Caries
  2: Periapical Lesion
  3: Deep Caries